version: '3.9'
services:
  acp-server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - "50051:50051"
    networks:
      - acp-network


  synthesizer:
    build:
      context: .
      dockerfile: docker/agent.Dockerfile
    environment:
      AGENT_ROLE: synthesizer
      ACP_ADDR: acp-server:50051
      OLLAMA_HOST: host.docker.internal:11434
      MODEL_NAME: qwen:0.6b
    networks:
      - acp-network
    depends_on:
      - acp-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./agents/conf:/app/agents/conf
    healthcheck:
      test: ["CMD", "python", "setup_model.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  sentinel:
    build:
      context: .
      dockerfile: docker/agent.Dockerfile
    environment:
      AGENT_ROLE: sentinel
      ACP_ADDR: acp-server:50051
      OLLAMA_HOST: host.docker.internal:11434
      MODEL_NAME: qwen:0.6b
    networks:
      - acp-network
    depends_on:
      - acp-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./agents/conf:/app/agents/conf
    healthcheck:
      test: ["CMD", "python", "setup_model.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  expert:
    build:
      context: .
      dockerfile: docker/agent.Dockerfile
    environment:
      AGENT_ROLE: expert
      ACP_ADDR: acp-server:50051
      OLLAMA_HOST: host.docker.internal:11434
      MODEL_NAME: qwen:0.6b
    networks:
      - acp-network
    depends_on:
      - acp-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./agents/conf:/app/agents/conf
    healthcheck:
      test: ["CMD", "python", "setup_model.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  observer:
    build:
      context: .
      dockerfile: observer/Dockerfile
    volumes:
      - ./logs:/logs
    environment:
      ACP_ADDR: acp-server:50051
    networks:
      - acp-network
    depends_on:
      - acp-server

networks:
  acp-network:
    driver: bridge
