version: '3.9'
services:
  acp-server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - "50051:50051"
    networks:
      - acp-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    networks:
      - acp-network

  synthesizer:
    build:
      context: .
      dockerfile: docker/agent.Dockerfile
    environment:
      AGENT_ROLE: synthesizer
      ACP_ADDR: acp-server:50051
      OLLAMA_HOST: ollama:11434
    networks:
      - acp-network
    depends_on:
      - ollama
      - acp-server

  sentinel:
    build:
      context: .
      dockerfile: docker/agent.Dockerfile
    environment:
      AGENT_ROLE: sentinel
      ACP_ADDR: acp-server:50051
      OLLAMA_HOST: ollama:11434
    networks:
      - acp-network
    depends_on:
      - ollama
      - acp-server

  expert:
    build:
      context: .
      dockerfile: docker/agent.Dockerfile
    environment:
      AGENT_ROLE: expert
      ACP_ADDR: acp-server:50051
      OLLAMA_HOST: ollama:11434
    networks:
      - acp-network
    depends_on:
      - ollama
      - acp-server

  observer:
    build:
      context: .
      dockerfile: observer/Dockerfile
    volumes:
      - ./logs:/logs
    environment:
      ACP_ADDR: acp-server:50051
    networks:
      - acp-network
    depends_on:
      - acp-server

networks:
  acp-network:
    driver: bridge
