version: '3.9'
services:
  acp-server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - "50051:50051"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL:-anthropic/claude-3-haiku}
    volumes:
      - ./logs:/app/logs

  synthesizer:
    build:
      context: .
      dockerfile: docker/agent.Dockerfile
    environment:
      AGENT_ROLE: synthesizer
      AGENT_ID: synthesizer-1
      ACP_ADDR: acp-server:50051
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      OPENROUTER_MODEL: ${OPENROUTER_MODEL:-anthropic/claude-3-haiku}
    depends_on:
      - acp-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./logs:/app/logs

  sentinel:
    build:
      context: .
      dockerfile: docker/agent.Dockerfile
    environment:
      AGENT_ROLE: sentinel
      AGENT_ID: sentinel-1
      ACP_ADDR: acp-server:50051
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      OPENROUTER_MODEL: ${OPENROUTER_MODEL:-anthropic/claude-3-haiku}
    depends_on:
      - acp-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./logs:/app/logs

  expert:
    build:
      context: .
      dockerfile: docker/agent.Dockerfile
    environment:
      AGENT_ROLE: expert
      AGENT_ID: expert-1
      ACP_ADDR: acp-server:50051
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      OPENROUTER_MODEL: ${OPENROUTER_MODEL:-anthropic/claude-3-haiku}
    depends_on:
      - acp-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./logs:/app/logs

  observer:
    build:
      context: .
      dockerfile: observer/Dockerfile
    volumes:
      - ./logs:/app/logs
    environment:
      ACP_ADDR: acp-server:50051
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    depends_on:
      - acp-server

volumes:
  acp-logs:
