version: '3.9'
services:
  acp-server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - "50051:50051"

  synthesizer:
    build:
      context: .
      dockerfile: docker/agent.Dockerfile
    environment:
      AGENT_ROLE: synthesizer
      ACP_ADDR: acp-server:50051
      OLLAMA_HOST: host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sentinel:
    build:
      context: .
      dockerfile: docker/agent.Dockerfile
    environment:
      AGENT_ROLE: sentinel
      ACP_ADDR: acp-server:50051
      OLLAMA_HOST: host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"

  expert:
    build:
      context: .
      dockerfile: docker/agent.Dockerfile
    environment:
      AGENT_ROLE: expert
      ACP_ADDR: acp-server:50051
      OLLAMA_HOST: host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"

  observer:
    build:
      context: ./observer
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
    environment:
      ACP_ADDR: acp-server:50051
